---
- name: Check for valid tags
  debug:
    msg: "Running play with {{ ansible_run_tags }}, provide either 'custom-chain' or 'cosmos-chain'"
  failed_when: "'custom-chain' not in ansible_run_tags and 'cosmos-chain' not in ansible_run_tags "

- name: Change hostname to inventory name
  hostname:
    name: "{{ inventory_hostname }}"

- name: Template /etc/hosts
  template:
    src: hosts.j2
    dest: /etc/hosts

- name: Template /etc/issue
  template:
    src: issue.j2
    dest: /etc/issue

- name: Check GO version
  shell: bash -ilc 'go version'
  register: go_current_version
  check_mode: false
  ignore_errors: true

- name: Remove old netcat
  apt:
    name: netcat-openbsd
    state: absent
  when: ansible_distribution == "Ubuntu"

- name: Install specified GO version
  block:
    - name: Download go
      get_url:
        url: "https://dl.google.com/go/go{{ go_version }}.linux-amd64.tar.gz "
        dest: /opt
        mode: 0755
    - name: Extract go
      unarchive:
        src: "/opt/go{{ go_version }}.linux-amd64.tar.gz"
        dest: /opt
        remote_src: true
      when: not ansible_check_mode
    - name: Install go
      copy:
        src: /opt/go
        dest: /usr/local
        remote_src: true
        mode: '0755'
      when: not ansible_check_mode
    - name: Create go vars in profile
      lineinfile:
        dest: /root/.profile
        regexp: "{{ item.regexp }}"
        line: "{{ item.line }}"
      loop:
        - { regexp: '^export\ GOROOT', line: 'export GOROOT=/usr/local/go' }
        - { regexp: '^export\ PATH=.*', line: 'export PATH=$GOPATH/bin:$GOROOT/bin:$PATH' }
        - { regexp: '^export\ GOPATH=.*', line: 'export GOPATH=/root/go/' }
  when: (go_current_version.stdout == "" and go_version is defined) or (go_current_version is defined and go_current_version.stdout_lines[0].split(' ')[2][2:] != go_version)

- name: Add lynis keys
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: 013baa07180c50a7101097ef9de922f1c2fde6c4
  when: ansible_distribution == "Ubuntu"

- name: Add lynis repo
  apt_repository:
    repo: deb https://packages.cisofy.com/community/lynis/deb/ stable main
    state: present
  when: ansible_distribution == "Ubuntu"

- name: Update repo listings
  apt:
    update_cache: true
  when: ansible_distribution == "Ubuntu"

- name: Install packages_custom
  package:
    state: present
    update_cache: false
    name: "{{ packages_custom | default([]) }}"
  when:
    - packages_custom is defined
