---
- name: Add group
  group:
    name: exporter
    state: present

- name: Add user
  user:
    name: exporter
    groups: exporter,gaiad
    shell: /sbin/nologin
    append: true
    state: present

- name: Create systemd service
  template:
    src: exporter.service.j2
    dest: /etc/systemd/system/exporter.service
  notify:
    - exporter enable
    - exporter restart
