---
- name: Clone repo
  git:
    repo: 'https://github.com/cronzevid/cosmos_exporter.git'
    dest: /opt/cosmos_exporter
    clone: true
    update: true
  register: repo_update

- name: Compile exporter
  shell: "source /root/.profile && go build -o cosmos-exporter"
  args:
    chdir: "/opt/cosmos_exporter"
    executable: /bin/bash
  when: repo_update.changed and not ansible_check_mode

- name: Copy exporter executable
  copy:
    src: /opt/cosmos_exporter/cosmos-exporter
    dest: /usr/local/bin/cosmos-exporter
    remote_src: true
    mode: '0755'
  when: not ansible_check_mode
  notify:
    - exporter restart
