---
- name: Clone repo
  git:
    repo: 'https://github.com/cronzevid/cosmos_exporter.git'
    dest: /opt/cosmos_exporter
    clone: true
    update: true

- name: Compile exporter
  shell: "source /root/.profile && go build -o cosmos_exporter"
  args:
    chdir: "/opt/cosmos_exporter-{{ cosmos_sdk_version }}"
    executable: /bin/bash
