- name: Deny everything and enable UFW
  ufw:
    state: enabled
    policy: deny

- name: Set logging
  ufw:
    logging: on

- name: Allow custom rules
  ufw:
    rule: {{ ufw_allow.rule }}
    port: {{ ufw_allow.port }}
    proto: {{ ufw_allow.proto }}
  with_items:
    - {{ ufw_allow }}
  when: ufw_allow is defined
