- name: Deny everything and enable UFW
  ufw:
    state: enabled
    policy: deny

- name: Set logging
  ufw:
    logging: true

- name: Allow custom rules
  ufw:
    rule: "{{ item.rule }}"
    port: "{{ item.port }}"
    proto: "{{ item.proto }}"
  with_items:
    - "{{ ufw_allow }}"
  when: ufw_allow is defined
