---
- name: Current pass keys
  command: pass ls
  register: pass_vault

- name: Create pass store
  block:
    - name: Generate GPG config
      template:
        src: gpg.conf.j2
        dest: /tmp/gpg.conf

    - name: Generate GPG key
      command: gpg --batch --gen-key --pinentry-mode=loopback --passphrase='' /tmp/gpg.conf

    - name: Get GPG key
      shell: "gpg --list-secret-keys | grep -A1 'sec.*rsa2048' | tail -1 | tr -d ' '"
      register: gpg_id

    - name: Set up password store
      command: "pass init {{ gpg_id.stdout }}"

    - name: Add key to keyring
      command: simd keys add my_validator --keyring-backend pass
      register: mnemonic

    - name: Save mnemonic
      copy:
        content: "{{ mnemonic.stderr_lines[-1] }}"
        dest: /opt/mnemonic

  when: '"my_validator" not in pass_vault.stdout'
