---
- name: Install Cosmos SDK
  get_url:
    url: http://example.com/path/file.conf
    dest: /etc/foo.conf
    mode: '0440'

- name: Generate GPG config
  template:
    src: gpg.conf.j2
    dest: /tmp/gpg.conf

- name: Generate GPG key
  command: gpg --batch --gen-key --pinentry-mode=loopback /tmp/gpg.conf
  register: gpg_id

- name: Set up password store
  command: pass init {{ gpg_id.stdout_lines[0].split(" ")[2]}}

- name: Add key to keyring
  command: simd keys add my_validator --keyring-backend pass
