---
- name: Check for Cosmos SDK dir
  stat:
    path: "/opt/cosmos-sdk-v{{ cosmos_sdk_version }}"
  register: archive_exists
  check_mode: true

- name: Install Cosmos SDK
  block:
    - name: Download SDK
      get_url:
        url: "https://github.com/cosmos/cosmos-sdk/archive/refs/tags/v{{ cosmos_sdk_version }}.tar.gz"
        dest: /opt
        mode: 0755
    - name: Extract SDK
      unarchive:
        src: "/opt/v{{ cosmos_sdk_version }}.tar.gz"
        dest: /opt
  when: !archive_exists
