---
ufw_allow:
  - rule: allow
    port: 22
    proto: tcp
  - rule: allow
    port: 26657
    proto: tcp
  - rule: allow
    port: 6060
    proto: tcp
  - rule: allow
    port: 26656
    proto: tcp
  - rule: allow
    port: 9090
    proto: tcp
