---
- hosts: cosmos_nodes
  gather_facts: true
  become: true
  roles:
    - role: common
      tags: [ 'always' ]
    - role: ufw
      tags: [ 'always' ]
    - role: custom_chain
      tags: [ 'custom-chain', 'never' ]
    - role: cosmos_chain
      tags: [ 'cosmos-chain', 'never' ]
    - role: exporter
      tags: [ 'always' ]
    - role: security
      tags: [ 'always' ]
