- name: Run audit
  shell: lynis audit system --nocolors | grep 'Hardening index'
  ignore_errors: true
  register: audit_result
  check_mode: false

- name: Output index
  debug:
    msg: "{{ audit_result.stdout }}"
  when: audit_result.stdout != ""
