---
- name: Check lynis version
  command: lynis lynis --version
  register: lynis_current_version
  ignore_errors: true

- name: Install specified lynis version
  block:
    - name: Download lynis
      get_url:
        url: "https://github.com/CISOfy/lynis/archive/refs/tags/{{ lynis_version }}.tar.gz"
        dest: /opt
        mode: 0755
    - name: Extract lynis
      unarchive:
        src: "/opt/lynis-{{ lynis_version }}.tar.gz"
        dest: /opt
        remote_src: true
      when: not ansible_check_mode
    - name: Install lynis
      copy:
        src: "/opt/lynis-{{ lynis_version }}/lynis"
        dest: /usr/local/bin/lynis
        remote_src: true
        mode: '0755'
      when: not ansible_check_mode
  when: (lynis_current_version is not defined and lynis_version is defined) or (lynis_current_version is defined and lynis_current_version != go_version)
