---
- name: Check gaiad version
  shell: bash -ilc 'gaiad version'
  register: gaiad_current_version
  ignore_errors: true

- name: Install specified gaiad version
  block:
    - name: Download gaiad
      get_url:
        url: "https://github.com/cosmos/gaia/releases/download/v{{ gaiad_version }}/gaiad-v{{ gaiad_version }}-linux-amd64"
        dest: /opt
        mode: 0755
    - name: Install gaiad
      command: "mv /opt/gaiad-v{{ gaiad_version }}-linux-amd64 /usr/local/bin/gaiad"
    - name: Init gaiad
      command: gaiad init my_cosmos_node
    - name: Download genesis
      get_url:
        url: "https://github.com/cosmos/mainnet/raw/master/genesis.cosmoshub-4.json.gz"
        dest: /opt
        mode: 0755
    - name: Extract genesis
      command: gunzip /opt/genesis.cosmoshub-4.json.gz
    - name: Move genesis
      command: cp /opt/genesis.cosmoshub-4.json ~/.gaia/config/genesis.json
  when: gaiad_version is defined and gaiad_current_version.stdout[1:] != gaiad_version
