---
- name: Create systemd service
  template:
    src: gaiad.service.j2
    dest: /etc/systemd/system/gaiad.service
  notify:
    - gaiad enable
    - gaiad restart

- name: Generate gaiad app config
  template:
    src: app.toml.j2
    dest: /root/.gaia/config/app.toml
  notify:
    - gaiad restart

- name: Generate gaiad config
  template:
    src: config.toml.j2
    dest: /root/.gaia/config/config.toml
  notify:
    - gaiad restart
