---
- name: Add group
  group:
    name: "{{ gaiad.user }}"
    state: present

- name: Add user
  user:
    name: "{{ gaiad.user }}"
    groups: "{{ gaiad.user }}"
    shell: /sbin/nologin
    append: true
    state: present

- name: Environment file
  template:
    src: gaiad_env.j2
    dest: /opt/gaiad_env

- name: Create systemd service
  template:
    src: gaiad.service.j2
    dest: /etc/systemd/system/gaiad.service
  notify:
    - gaiad enable
    - gaiad restart

- name: Generate gaiad app config
  template:
    src: app.toml.j2
    dest: "/home/{{ gaiad.user }}/.gaia/config/app.toml"
  notify:
    - gaiad restart

- name: Generate gaiad config
  template:
    src: config.toml.j2
    dest: "/home/{{ gaiad.user }}/.gaia/config/config.toml"
  notify:
    - gaiad restart
